---
abstract: 'use C<IO::Async> with C<Mojolicious>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Async-Loop-Mojo
provides:
  IO::Async::Loop::Mojo:
    file: lib/IO/Async/Loop/Mojo.pm
    version: 0.04
requires:
  IO::Async::Loop: 0.49
  Mojolicious: 2.65
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
